# Generated by Django 3.2.4 on 2021-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmoScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achat_valeur_bien', models.FloatField(default=0)),
                ('achat_notaire_taux', models.FloatField(default=0)),
                ('achat_apport_personnel', models.FloatField(default=0)),
                ('achat_emprunt_capital', models.FloatField(default=0)),
                ('achat_emprunt_taux', models.FloatField(default=0)),
                ('loca_montant_loyer', models.FloatField(default=0)),
                ('loca_charges', models.FloatField(default=0)),
                ('compta_amortissement_duree', models.FloatField(default=0)),
            ],
        ),
    ]
