# Generated by Django 3.2.4 on 2021-06-26 19:27

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('immoScenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immoscenario',
            name='created_date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='immoscenario',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
